# Generated by Django 3.2.8 on 2021-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('question', 'Pytanie'), ('other', 'Inne')], max_length=10),
        ),
    ]
