# Generated by Django 3.2.8 on 2021-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp_5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='abc', max_length=32),
            preserve_default=False,
        ),
    ]
