# Generated by Django 3.2.8 on 2021-11-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp_5', '0002_task_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
